title: Ein Titel
author: Author
email: test@test.de
description: > # this means to ignore newlines until "show_exerpts:"
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est .
main_image: http://placekitten.com/900/600
show_excerpts: false # set to true to show excerpts on the homepage

license:
  holder: Open Knowledge Foundation Deutschland
  license: License CC BY-SA 3.0
mainpage:
  url: //your-actual-website.tld
  pdf: /fake/link/to.pdf
  label: Go back to your actual website
  year: 2018
chapter:
  resources: Ressourcen
  effects:
    - label: Das Problem
      key: problem
    - label: Mögliche Ursachen
      key: causes
    - label: Lösungsansatz
      key: solution
    - label: Angestrebte Wirkung
      key: effect
  outcomes:
    - label: Erbrachte Leistungen
      key: achievements
    - label: Output
      key: outputs
    - label: Outcome
      key: outcome
    - label: Impact
      key: impact
    - label: Evaluation
      key: evaluation
    - label: Ausblick
      key: outlook

# matomo:
#   url: //to-your-matomo.tdl
#   id: projectID

# Build settings
theme: okf-pub-theme

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
